config/routes.rb
Rails.application.routes.draw do
  resources :modal
  resources :posts
  resource :hide_from_backend, only: [:new, :create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SetFlavor

  def set_modal_properties
    @padding = !(params[:padding] == "0")
    @advance = params[:advance] == "1"
    @override_url = "/custom-advance-history-url" if @advance
  end
end

app/controllers/concerns/set_flavor.rb
module SetFlavor
  extend ActiveSupport::Concern

  included do
    before_action do
      UltimateTurboModal.flavor = request.params[:flavor] || cookies[:flavor] || "tailwind"
      cookies.permanent[:flavor] = UltimateTurboModal.flavor
    end
  end
end

app/controllers/hide_from_backends_controller.rb
# Sometimes it might be desirable to close the modal from the backend.
# This can be done with Turbo Stream as such:
#
#   <%= turbo_stream.modal(:hide) %>
#
# This controller is an example of how to do that.
class HideFromBackendsController < ApplicationController
  def new
    # Show form
  end

  def create
    form_is_valid? ? close_modal : render(:new, status: :unprocessable_entity)
  end

  private

  def close_modal
    if inside_modal?
      # `create.turbo_stream.erb` will be rendered.
      # A message will appear in the browser, and the backend
      # will trigger a modal close via turbo stream.
    else
      # if not inside a modal, simply redirect
      redirect_to("/")
    end
  end

  def form_is_valid?
    return true if request[:action] == 'new'
    params[:email].present?
  end
  helper_method :form_is_valid?
end

app/controllers/modal_controller.rb
class ModalController < ApplicationController
  before_action :set_modal_properties

  def index
    @post = Post.first
  end

  def show
    @header = !(params[:id] == "photo")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :set_modal_properties

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
    @modal_title = @post.title
  end

  # GET /posts/new
  def new
    @post = Post.new
    @modal_title = "New Post"
  end

  # GET /posts/1/edit
  def edit
    @modal_title = "Edit Post"
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to "/",
                  notice: "Post was successfully created.",
                  status: :see_other
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to "/",
                  notice: "Post was successfully updated.",
                  status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    redirect_to "/",
                notice: "Post was successfully destroyed. (but not really)",
                status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def h1_classes
    "text-2xl font-bold tracking-tight text-gray-900 sm:text-4xl border-b mb-2 dark:text-white"
  end

  def button_classes
    "rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
  end
end

app/views/hide_from_backends/_notice.html.erb
<% if local_assigns[:message] %>
  <div id="#ts-notice" class="fixed top-2 right-2 w-auto border p-4 my-10 text-black border-green-800 bg-green-200 max-w-lg">
    <%= local_assigns[:message] %>
    <div class="mt-3 font-medium">
      <a href="#" onclick="document.querySelector('#ts-notice')?.innerHTML=''; return false;">Close</a>
    </div>
  </div>
<% else %>
  <div id="#ts-notice"></div>
<% end %>

app/views/hide_from_backends/create.turbo_stream.erb
<%= turbo_stream.replace "#ts-notice", partial: "notice", locals: { message: "Modal close was triggered by the backend via Turbo Stream @ #{Time.now}!" } %>
<%= turbo_stream.modal(:hide) %>

app/views/hide_from_backends/new.html.erb
<%= modal(title: "My Glorious Form") do %>
  <% if !inside_modal? %>
    <div class="px-4 py-5 sm:p-3">
      <h3 class="text-base font-semibold leading-6 text-gray-900">My Glorious Form</h3>
  <% end %>

    <div class="mt-2 max-w-xl text-sm text-gray-500 dark:text-white">
      <p>Upon submission, the modal will be closed from the backend.</p>
      <p class="mt-2">If no email is entered, the form will be redisplayed with errors.</p>
    </div>

    <% if !form_is_valid? %>
      <div class="my-4 text-red-700 font-semibold">
        Email is required!
      </div>
    <% end %>

    <%= form_with url: hide_from_backend_path, method: :post, class: "mt-5 sm:flex sm:items-center" do %>
      <div class="w-full sm:max-w-xs">
        <label for="email" class="sr-only">Email</label>
        <input type="email" name="email" id="email" class="block w-full rounded-md border-0 py-1.5 text-gray-900 ring-gray-300 shadow-sm ring-1 ring-inset placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="you@example.com">
      </div>

      <button type="submit" class="mt-3 inline-flex w-full items-center justify-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:ml-3 sm:mt-0 sm:w-auto">Save</button>
    <% end %>

  <% if !inside_modal? %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="<%= cookies[:theme] == "dark" ? "dark" : "" %>">
  <head>
    <title>Ultimate Turbo Modal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://unpkg.com/idiomorph"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="dark:bg-slate-800 dark:text-white transition-colors">
    <%= turbo_frame_tag "modal" %>
    <%= render partial: "shared/flash" %>

    <div class="container mx-auto mt-8 px-5 bg-white dark:bg-slate-800 transition-colors">
      <%= yield %>
    </div>

    <div class="fixed right-4 top-4 h-6 text-black dark:text-white" data-controller="dark-mode">
      <button data-action="click->dark-mode#toggleTheme">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 dark:hidden">
          <path stroke-linecap="round" stroke-linejoin="round" d="M21.752 15.002A9.718 9.718 0 0118 15.75c-5.385 0-9.75-4.365-9.75-9.75 0-1.33.266-2.597.748-3.752A9.753 9.753 0 003 11.25C3 16.635 7.365 21 12.75 21a9.753 9.753 0 009.002-5.998z" />
        </svg>

        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 hidden dark:block">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
        </svg>
      </button>
    </div>

    <a href="/">
      <% if UltimateTurboModal.flavor == :tailwind %>
        <svg class="fixed right-4 bottom-4 h-12" viewBox="0 0 50 31" class="text-slate-900 dark:text-white w-auto h-5"><path fill-rule="evenodd" clip-rule="evenodd" d="M25.517 0C18.712 0 14.46 3.382 12.758 10.146c2.552-3.382 5.529-4.65 8.931-3.805 1.941.482 3.329 1.882 4.864 3.432 2.502 2.524 5.398 5.445 11.722 5.445 6.804 0 11.057-3.382 12.758-10.145-2.551 3.382-5.528 4.65-8.93 3.804-1.942-.482-3.33-1.882-4.865-3.431C34.736 2.92 31.841 0 25.517 0zM12.758 15.218C5.954 15.218 1.701 18.6 0 25.364c2.552-3.382 5.529-4.65 8.93-3.805 1.942.482 3.33 1.882 4.865 3.432 2.502 2.524 5.397 5.445 11.722 5.445 6.804 0 11.057-3.381 12.758-10.145-2.552 3.382-5.529 4.65-8.931 3.805-1.941-.483-3.329-1.883-4.864-3.432-2.502-2.524-5.398-5.446-11.722-5.446z" fill="#38bdf8"></path></svg>
      <% elsif UltimateTurboModal.flavor == :bootstrap %>
        <img class="fixed right-4 bottom-4 h-14" src="/img/bootstrap-logo-shadow.png">
      <% elsif UltimateTurboModal.flavor == :vanilla %>
        <img class="fixed right-4 bottom-4 h-16" src="/img/vanilla.png">
      <% end %>
    </a>
  </body>
</html>

app/views/modal/index.html.erb
<%= render partial: "hide_from_backends/notice" %>
<div class="fixed left-3 bottom-3 text-lg text-gray-600">
  Rendered at <%= Time.now %>
</div>

<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <!-- We've used 3xl here, but feel free to try other max-widths based on your needs -->
  <div class="mx-auto max-w-3xl space-y-24">
    <div>
      <h1 class="<%= h1_classes %>">CRUD modals</h1>
      <ul class="list-disc ml-6 dark:text-white">
        <li class="py-2"><%= link_to "Show Post", post_path(@post), data: {turbo_frame: "modal"} %>
        <li class="py-2"><%= link_to "New Post", new_post_path(Post.new), data: {turbo_frame: "modal"} %>
        <li class="py-2"><%= link_to "Show Post (w/ advance history)", post_path(@post, advance: "1"), data: {turbo_frame: "modal"} %>
      </ul>
    </div>

    <div>
      <h1 class="<%= h1_classes %>">More modals</h1>
      <ul class="list-disc ml-6 dark:text-white">
        <li class="py-2"><%= link_to "Photo with no header and padding", modal_path(:photo, padding: 0, advance: 1), data: {turbo_frame: "modal"} %>
        <li class="py-2"><%= link_to "Long scrolling content", modal_path(:long, advance: 1), data: {turbo_frame: "modal"} %>
        <li class="py-2"><%= link_to "Form closing from backend on success", new_hide_from_backend_path, data: {turbo_frame: "modal"} %>
      </ul>
    </div>
  </div>
</div>


<div class="mx-auto text-center">
  <% 30.times do %>
    <div class="my-48 text-gray-300 mx-auto">
      This is a long page!
    </div>
  <% end %>
</div>

<div class="my-20 text-center">
  <%= link_to "Click for a unicat", modal_path(:photo, padding: 0, advance: 1), class: button_classes, data: {turbo_frame: "modal"} %>
</div>

app/views/modal/show.html.erb
<%= modal(padding: @padding, advance: @override_url || @advance, header: @header) do %>
  <% unless inside_modal? %>
    <h1 class="text-2xl mb-8">This is not inside a modal</h1>
  <% end %>

  <% if params[:id] == "long" %>
    <div class="space-y-2 max-w-3xl">
      <% 30.times do %>
        <p><%= Faker::Lorem.paragraph(sentence_count: 50) %></p>
      <% end %>
    </div>
  <% elsif params[:id] == "photo" %>
    <div class="w-full">
      <img src="/img/unicat.jpg">
    </div>
  <% else %>
    <div class="w-full">
      Not sure what you're looking for!
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="w-96">
  <%= form_with(model: post, class: "contents") do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="my-5">
      <%= form.label :body %>
      <%= form.text_field :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <% if !inside_modal? %>
    <h3 class="mb-5 text-lg font-semibold"><%= @post.title %></h3>
  <% end %>

  <p class="my-5">
    <%= post.body %>
  </p>
</div>

app/views/posts/edit.html.erb
<%= modal(title: "Editing Post") do |m| %>
  <div class="mx-auto w-96">
    <% if !inside_modal? %>
      <h1 class="font-bold text-4xl">Editing post</h1>
    <% end %>

    <%= render "form", post: @post, modal: m %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= modal(padding: @padding, advance: @override_url || @advance, title: @modal_title) do %>
  <%= render "form", post: @post %>
<% end %>

app/views/posts/show.html.erb
<%= modal(padding: @padding, advance: @override_url || @advance, title: @modal_title) do |m| %>
  <div class="max-w-3xl">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>
  </div>

  <%= m.footer do %>
    <%= link_to 'Edit this post', edit_post_path(@post), class: "rounded-lg py-3 px-5 bg-blue-800 text-white inline-block font-medium" %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "py-3 px-5 bg-transparent text-red-600" %>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="px-5 py-2 absolute top-3 right-3" data-controller="flash">
    <% flash.each do |key, value| %>
      <% if key == "alert" %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <% else %>
        <div class="bg-indigo-100 border border-indigo-400 text-indigo-700 px-4 py-3 rounded relative" role="notice">
      <% end %>
        <span class="block sm:inline"><%= value %></span>
      </div>
    <% end %>
  </div>
<% end %>